### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-bezsonov#3]
Запитання
3) Відомо, що Git-система контроля версій використовує запити Pull Request. 
Поясніть, будь ласка, як використання такого запиту може підвищити 
безпеку процесів створення програмного продукту?

**Comment by Desken-van** [comment]
По-перше перевірка та рецензія коду. Перед тим як почати Merge можна побачити зміни у проекті (Запобігання випадкових змін коду). 
Також важливо якщо процесс йде у команді, бо члени команди можуть проглянути код, та надати рекомендації щодо його удосконалення (Clean code). 
На цьому етапі можна скорегувати також права доступу до PR та його Merge.  Таким чином, хоча й уся команда буде роздивлятися та надавати свої рекомендації до коду, але виконати а апрувнути мердж зможуть тількі ті у кого його на те право. Таким чином не буде випадкових мерджів, у усі вони будуть заплановані (Що вирішує побутові проблеми які виникають у роботі в команді з кодом.)
Також можна додати статичні аналізатори для автоматизування перевірки коду, для того щоб пришвидшити процес ревью

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
